#!/bin/bash

command=$1
shift

if [[ $command == "start" ]]; then
	./bin/start-server $@
elif [[ $command == "create" ]]; then
	./bin/create-component $@
elif [[ $command == "add" ]]; then
	./bin/add-component $@
elif [[ $command == "install" ]]; then
	./bin/install $@
else
	echo "Command \"$command\" not found."
	exit 1
fi
