#!/usr/bin/env node
// @ts-nocheck
'use strict';

const {
	action,
	bot,
	bootstrap
} = require("../../component");

const nlp = require('../../nlp');
const data = require("./data.json");

const component = bot(
	require("./responses.json"),
	{
		index: (msg, state, responses, send, route) => {
			if (state.context.user)
				route("welcome_user");
			else
				route("verify_user");
		},
		welcome_user: action.exit(), // We never made anything past this...

		// Call upon our "verify user" component:
		verify_user: action.bot("verify_user", (response, state, send, route, pass) => {
			pass("welcome_user", response);
		}),

		// Exit for now... TODO: continue to rest of the app.
		exit: action.exit()
	});

// Hooks our bot into the appropriate IO:
bootstrap(component);
