#!/usr/bin/env node
// @ts-nocheck
'use strict';

const {
	action,
	bot,
	bootstrap
} = require("../../component");

const nlp = require('../../nlp');
const data = require("./data.json");

const component = bot(
	require("./responses.json"),
	{
		index: (msg, state, responses, send, route) => {
			if (state.context.user)
				route("welcome_user");
			else
				route("verify_user");
		},
		welcome_user: action.default("menu"),
		verify_user: action.bot(
			"verify_user",
			context => "welcome_user",
			context => "verify_user",
			context => "signup_prompt"),

		signup_prompt: action.default("signup_confirm"),
		signup_confirm: action.confirm("signup_form", "menu"),

		signup_form: action.bot("signup", context => "welcome_user"),

		/* The menu is our meat and potatoes... */
		menu: (msg, state, responses, send, route) => {
			send("menu", responses.random().render({}));
		},
		menuitem_done: action.default("menu"),

		company_details: action.default("menuitem_done"),
		locations: action.default("menuitem_done"),
		location_details: action.default("menuitem_done"),
		products: action.default("menuitem_done"),
		stock_availability: action.default("menuitem_done"),


		goodbye: action.bot("goodbye", context => "exit"),
		exit: action.exit(),
	});

// Hooks our bot into the appropriate IO:
bootstrap(component);
