#!/usr/bin/env node
// @ts-nocheck
'use strict';

const {
	action,
	bot,
	bootstrap
} = require("../../component");

const nlp = require('../../nlp');

const component = bot(
	require("./responses.json"),
	{
		index: action.default('verify_email'),
		verify_email: (msg, state, responses, send, route, pass) => {
			// TODO: verify the email... then route to "email_verified"
			// This uses OUR database to check if the user exists :)
			console.log('VERIFY EMAIL FUNCTION!');
			route("email_verified");
		},
		email_verified: action.exit()
	});

// Hooks our bot into the appropriate IO:
bootstrap(component);
