#!/usr/bin/env node
// @ts-nocheck
'use strict';

const {
	action,
	bot,
	bootstrap
} = require("../../component");

const {
	info
} = require('../../models');

const nlp = require('../../nlp');

const component = bot(
	require("./responses.json"),
	{
		index: action.default('verify_email'),
		verify_email: (msg, state, responses, send, route, pass) => {
			let email = nlp.email.exec(msg)[0];
			if (email) {
				state.context.userInfo = info(email);
				route("email_verified");
			} else
				route("email_invalid");
		},
		email_invalid: action.default("verify_email"),
		email_verified: action.exit()
	});

// Hooks our bot into the appropriate IO:
bootstrap(component);
