#!/usr/bin/env node
// @ts-nocheck
'use strict';

const {
	action,
	bot,
	bootstrap
} = require("../../component");

const nlp = require('../../nlp');

/*

	Bank Bot - Bot Component
	Author: Graham Robertson

*/

const component = bot(
	require("./responses.json"),
	{
		// App entry point:
		index: (msg, context, state, responses, send) => {
			// Do some stuff with msg then maybe wait for an
			// API call or asynchronous operation... then call send.
			send(
				// Next action name:
				"action_name",
				// Response text:
				responses.random().render({
					/* response render context */
				}),
				// Updated context:
				context
			);
		},

		welcome_user: action.default("welcome_user", context => "menu"),
		signup_prompt: action.bot("signup_prompt", context => context.completed ? "signup" : "any_questions"),
		
		signup: action.bot("bank.signup", context => "welcome_user"),
		any_questions: (msg, ontext, state, responses, send) => {
			// Try to find what our user might need help with outside
			// of being a user of the bank...
		},

		menu: (msg, context, state, responses, send) => {
			// Do some stuff with msg then maybe wait for an
			// API call or asynchronous operation... then call send.
			send(
				// Next action name:
				// (based on the menu item we were looking for...)
				"action_name",
				// Response text:
				responses.random().render({
					/* response render context */
				}),
				// Updated context:
				context
			);
		},
		menu_help: action.default("menu"), // go back to menu...

		open_account: action.bot("bank.open_account"),
		replace_card: action.bot("bank.replace_card"),
		check_balance: action.bot("bank.check_balance"),
		transfer_funds: action.bot("bank.transfer_funds"),
		pay: action.bot("bank.pay"),

		goodbye: action.bot("goodbye"),
	});

// Hooks our bot into the appropriate IO:
bootstrap(component);
