#!/usr/bin/env node
// @ts-nocheck
'use strict';

const {
	action,
	bot,
	bootstrap
} = require("../../component");

const nlp = require('../../nlp');

const component = bot(
	require("./responses.json"),
	{
		// Entry point:
		index: action.default("confirm"),
		// We're looking for a yes or no here... depending on the answer,
		// we "route" to the appropriate action:
		confirm: action.confirm(
			"email",
			"verify_cancelled",
			"not_understood"
		),
		// Call upon our "email" component:
		email: action.bot('email', (response, state, send, route, pass) => {
			// TODO: check the state to see if we were successful

			// "pass" allows us to couple this response with the
			// next action in this conversation flow...
			pass('verify_passphrase', response);
		}),
		// Say we don't understand and then go back to confirm:
		not_understood: action.default("confirm"),
		// Exit the component:
		verify_cancelled: action.exit(),

		verify_passphrase: action.bot('verify_passphrase', (response, state, send, route, pass) => {
			pass('exit', response);
		}),

		exit: action.exit()
	});

// Hooks our bot into the appropriate IO:
bootstrap(component);
