#!/usr/bin/env node
// @ts-nocheck
'use strict';

const {
	action,
	bot,
	bootstrap
} = require("../../component");

const nlp = require('../../nlp');

const component = bot(
	require("./responses.json"),
	{
		index: action.default("confirm"),
		confirm: action.confirm("ask_email", "goodbye", "exit"),
		ask_email: action.default("verify_email"),
		verify_email: (msg, state, responses, send, route) => {
			if (nlp.no.test(msg))
				return route("exit");

			let email = nlp.email.exec(msg);

			console.log('>>', email);
			
			if (email) {
				state.context.userInfo = {
					email: email,
				};

				route("ask_passphrase");
			} else {
				route("user_not_found");
			}
		},
		user_not_found: action.default("verify_email"),
		ask_passphrase: action.default("verify_passphrase"),
		verify_passphrase: (msg, state, responses, send, route) => {
			if (nlp.no.test(msg))
				return route("bad_exit");

			console.log(msg);

			if (msg === "hnn")
				route("good_exit")
			else
				route("passphrase_denied")
		},
		passphrase_denied: action.default("verify_passphrase"),
		good_exit: action.exit(),
		bad_exit: action.exit()
	});

// Hooks our bot into the appropriate IO:
bootstrap(component);
