#!/usr/bin/env node
// @ts-nocheck
'use strict';

const {
	action,
	bot,
	bootstrap
} = require("../../component");

const nlp = require('../../nlp');

const component = bot(
	require("./responses.json"),
	{
		index: action.default("confirm"),
		confirm: action.confirm(
			"ask_email",
			"verify_cancelled",
			"not_understood"
		),
		ask_email: action.default("verify_email"),
		verify_email: (msg, state, responses, send, route, pass) => {
			// TODO: verify the email... then route to "email_verified"
			console.log('HEREEE');
			route("email_verified");
		},
		email_verified: action.pass("ask_passphrase"),
		verify_cancelled: action.exit(),

		ask_passphrase: action.default("verify_passphrase"),
		verify_passphrase: (msg, state, responses, send, route, pass) => {
			// TODO: verify passphrase... then route to "passphrase_verified"
			route("passphrase_verified");
		},
		passphrase_verified: action.exit()
	});

// Hooks our bot into the appropriate IO:
bootstrap(component);
